name: Pull Request Notifications

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: bhatch/discord-webhook@v1.0.1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: 'A new pull request has been created: ${{ github.event.pull_request.html_url }}'
